name: telegram notify
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          ⚡️ <em> <a href="https://github.com/paradoxxl/gomastermind">Repo updated by</a> ${{ github.actor }}</em> ⚡️ 
          commit message is ${{ github.event.head_commit.message }}
          Go to commit directly <a href="https://github.com/paradoxxl/gomastermind/commit/${{ github.sha }}">here</a>
