name: telegram notify
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <em> <a href="https://github.com/paradoxxl/gomastermind">Updated version available</a> <em> User ${{ github.event.push.pusher.name }}</em> ⚡️
          ${{ github.actor }} commit message ${{ github.event.head_commit.message }}
          Go to commit <a href="https://github.com/paradoxxl/gomastermind/commit/${{ github.sha }}">here</a>
